name: Guardception
description: A plugin to let players define regions only inside certain regions
version: 1.0.0
author: EspaCoder
main: com.reztech.guardception.Guardception
api-version: 1.15
depend: [WorldGuard, WorldEdit]
website: https://github.com/EspaCoder/Guardception
commands:
  gception:
    description: "Gives player the permission to define regions inside a certain region."
    usage: /gception (add | del | check) <player> <regionname>
    permission: guardception.subreg
    permission-message: "You don't have the permission to do this!"